baseURL = "https://irfanywz.web.id/"
theme = "hugo-ywz"
locale = "en-us"
title = "Muhamad Irfan"
copyright = "Muhamad Irfan"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

pagination.pagerSize = 2

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
  version = "2.1.0"
	# browser icon
  favicon = "favicon.ico"

	# Optional 64x64 avatar image.
	# avatar = "https://avatars.githubusercontent.com/u/117440754?v=4"
  avatar = "avatar.avif"

  author = "Muhamad Irfan"
  description = "Personal web Muhamad Irfan, menulis dan berbagi hal menarik seputar teknologi."
  keywords = "Muhamad Irfan, Content Creator Indonesia, YouTube Automation, Creator Tools, Digital Storytelling, muhamadirfan300899, Promise ETY, Bogor, Video Strategist, Personal Blog, sedang mempelajari bangun channel youtube yang menghasilkan, dengan harapan tahun ini bisa terkumpul 3 digit 000 xixixix"

# Menu Header
[[menu.main]]
name = "Beranda"
url = "/"
pre = "icon-[ri--home-line]"
weight = 10

[[menu.main]]
name = "Portofolio"
url = "/portofolio/"
pre = "icon-[ri--briefcase-2-line]"
weight = 36

# [[menu.main]]
# name = "Belajar"
# url = "/learn/"
# pre = "icon-[ri--lightbulb-line]"
# weight = 30

[[menu.main]]
name = "Layanan"
url = "/shop/"
pre = "icon-[ri--store-2-line]"
weight = 35

# [[menu.main]]
# name = "Kontak"
# url = "/contact/"
# pre = "icon-[ri--mail-line]"
# weight = 40

[[menu.main]]
name = "Tentang"
url = "/about/"
pre = "icon-[ri--user-line]"
weight = 40

# menu offcanvas
# ======================


[[menu.footer]]
name = "Jurnal"
url = "/journal/"
pre = "icon-[ri--newspaper-line]"
weight = 20
[menu.footer.params]
  color = "text-amber-500"

# [[menu.footer]]
# name = "Portofolio"
# url = "/portofolio/"
# pre = "icon-[ri--briefcase-2-line]"
# weight = 30
# [menu.footer.params]
#   color = "text-indigo-500"  

[[menu.footer]]
name = "Belajar"
url = "/learn/"
pre = "icon-[ri--lightbulb-line]"
weight = 30
[menu.footer.params]
  color = "text-sky-500"


[[menu.footer]]
name = "Musik"
url = "/music-playlist/"
pre = "icon-[ri--music-2-line]"
weight = 42
[menu.footer.params]
  color = "text-violet-500"

[[menu.footer]]
name = "Alat"
url = "/tools/"
pre = "icon-[ri--tools-line]"
weight = 60
[menu.footer.params]
  color = "text-orange-500"

[[menu.footer]]
name = "Koleksi"
url = "/collection/"
pre = "icon-[ri--stack-line]"
weight = 80
[menu.footer.params]
  color = "text-blue-500"

[[menu.footer]]
name = "Kontak"
url = "/contact/"
pre = "icon-[ri--mail-line]"
weight = 100
[menu.footer.params]
  color = "text-sky-500"

# [[menu.footer]]
# name = "Layanan"
# url = "/shop/"
# pre = "icon-[ri--store-2-line]"
# weight = 35
# [menu.footer.params]
#   color = "text-sky-500"

# menu bottom mobile
# ======================

[[menu.bottom]]
name = "Beranda"
url = "/"
pre = "icon-[ri--home-line]"
weight = 10


[[menu.bottom]]
name = "Portofolio"
url = "/portofolio/"
pre = "icon-[ri--briefcase-2-line]"
weight = 36

# [[menu.bottom]]
# name = "Belajar"
# url = "/learn/"
# pre = "icon-[ri--lightbulb-line]"
# weight = 30

# menu shop
[[menu.bottom]]
name = "Layanan"
url = "/shop/"
pre = "icon-[ri--store-2-line]"
weight = 35


[[menu.bottom]]
name = "Tentang"
url = "/about/"
pre = "icon-[ri--user-line]"
weight = 40

# [[menu.bottom]]
# name = "Kontak"
# url = "/contact/"
# pre = "icon-[ri--mail-line]"
# weight = 40

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    # hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "dracula"  # or any other chroma style
    tabWidth = 4

[taxonomies]
  tag = 'tags'

# allow html to content .md
[markup.goldmark.renderer] 
	unsafe= true

# allow shortcodes
[security]
	enableInlineShortcodes = true	

# output format
[outputs]
  home = ["HTML", "RSS", "JSON"]  

[outputFormats]
[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true
  notAlternative = true  

[languages.id]
label = "Indonesian"
locale = "id"

[services]
  [services.googleAnalytics]
    id = 'G-VVGW3VPZZG'
