baseURL = "https://irfanywz.web.id/"
theme = "hugo-ywz"
locale = "en-us"
title = "Personal blog Muhamad Irfan"
copyright = "Muhamad Irfan"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

pagination.pagerSize = 4

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  # title for seo
  title = "irfanywz"
  address = "irfanywz.web.id"


	# browser icon
  favicon = "favicon.ico"

	# Optional 64x64 avatar image.
	# avatar = "https://avatars.githubusercontent.com/u/117440754?v=4"
  avatar = "avatar.avif"
  logo = "logo.avif"
  logoText = "logo-text.avif"

  author = "Muhamad Irfan"
  description = "Personal blog Muhamad Irfan, menulis dan berbagi hal menarik seputar teknologi."
  keywords = "Muhamad Irfan, Konten kreator pemula, lagi belajar Storytelling, muhamadirfan300899, Bogor, Personal Blog"

  # ads on post
  showAds = false 
  adInterval = 4
  adCode = '''
    <div class="w-full">
        <span class="block text-xs font-semibold tracking-wider text-gray-400 uppercase mb-2">Advertisement</span>
        <div class="text-sm text-gray-500 dark:text-gray-400">
            <!-- Contoh jika pakai script AdSense atau banner kustom -->
            <span>-- Slot Iklan Global dari Confige --</span>
        </div>
    </div>
  '''

  # categories sidebar
  showCategories = true

  # ads sidebar
  showAdsSidebar = false
  adCodeSidebar = '''
    <div class="w-full">
        <span class="block text-xs font-semibold tracking-wider text-gray-400 uppercase mb-2">Advertisement</span>
        <div class="text-sm text-gray-500 dark:text-gray-400">
            <!-- Contoh jika pakai script AdSense atau banner kustom -->
            <span>-- Slot Iklan Global dari Config --</span>
        </div>
    </div>
  '''

  # Exit Popup
  exitIntentTitle = "Tunggu, Jangan Pergi"
  exitIntentContent = "Terima kasih telah mampir keblog ini"


# Menu Header
[[menu.main]]
name = "Beranda"
url = "/"
pre = "icon-[ri--home-line]"
weight = 10

[[menu.main]]
name = "Topik"
url = "/topics/"
pre = "icon-[ri--hashtag]"
weight = 20


[[menu.main]]
name = "Layanan"
url = "/services/"
pre = "icon-[ri--store-2-line]"
weight = 30

[[menu.main]]
name = "Kontak"
url = "/contact/"
pre = "icon-[ri--mail-line]"
weight = 35

[[menu.main]]
name = "Tentang"
url = "/about/"
pre = "icon-[lucide--user-round-pen]"
weight = 40



# menu offcanvas
# ======================

# --- Menu yang Ingin Disembunyikan ke dalam Dropdown "Lainnya" ---

[[menu.footer]]
name = "Jurnal"
url = "/journal/"
pre = "icon-[ri--newspaper-line]"
weight = 20
[menu.footer.params]
  color = "text-amber-500"
  # group = "dropdown"

# [[menu.footer]]
# name = "Musik"
# url = "/music-playlist/"
# pre = "icon-[ri--music-2-line]"
# weight = 42
# [menu.footer.params]
#   color = "text-violet-500"
  # group = "dropdown"

[[menu.footer]]
name = "Alat"
url = "/tools/"
pre = "icon-[ri--tools-line]"
weight = 60
[menu.footer.params]
  color = "text-orange-500"
  # group = "dropdown"

[[menu.footer]]
name = "Koleksi"
url = "/collection/"
pre = "icon-[ri--stack-line]"
weight = 80
[menu.footer.params]
  color = "text-blue-500"
  # group = "dropdown"

# menu bottom mobile
# ======================

[[menu.bottom]]
name = "Beranda"
url = "/"
pre = "icon-[ri--home-line]"
weight = 10

[[menu.bottom]]
name = "Topik"
url = "/topics/"
pre = "icon-[ri--hashtag]"
weight = 20

[[menu.bottom]]
name = "Layanan"
url = "/services/"
pre = "icon-[ri--store-2-line]"
weight = 30

[[menu.bottom]]
name = "Kontak"
url = "/contact/"
pre = "icon-[ri--mail-line]"
weight = 35

[[menu.bottom]]
name = "Tentang"
url = "/about/"
pre = "icon-[lucide--user-round-pen]"
weight = 40


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "dracula"  # or any other chroma style
    tabWidth = 2

[taxonomies]
  # tag = 'tags'
  topic = "topics"

[permalinks]
  posts = "/:slug/"

# allow html to content .md
[markup.goldmark.renderer] 
	unsafe= true

# allow shortcodes
[security]
	enableInlineShortcodes = true	

# output format
[outputs]
  home = ["HTML", "JSON", "RSS"]  
  section = ["HTML"] #force section only generate HTML not with RSS

[outputFormats] 
[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true
  notAlternative = true    

[languages.id]
label = "Indonesian"
locale = "id"

[services]
  [services.googleAnalytics]
    id = 'G-VVGW3VPZZG'